name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        if: hashFiles('package.json') != ''

      - name: Install dependencies
        run: npm ci
        if: hashFiles('package.json') != ''

      - name: Run linter
        run: npm run lint
        if: hashFiles('package.json') != ''

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        if: hashFiles('package.json') != ''

      - name: Install dependencies
        run: npm ci
        if: hashFiles('package.json') != ''

      - name: Run tests
        run: npm test
        if: hashFiles('package.json') != ''

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: hashFiles('coverage/') != ''
        with:
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
        if: hashFiles('package.json') != ''

      - name: Install dependencies
        run: npm ci
        if: hashFiles('package.json') != ''

      - name: Build
        run: npm run build
        if: hashFiles('package.json') != ''

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: hashFiles('dist/') != '' || hashFiles('build/') != ''
        with:
          name: build
          path: |
            dist/
            build/
          retention-days: 7

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run security audit
        run: npm audit --audit-level=high
        if: hashFiles('package.json') != ''
        continue-on-error: true

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
        if: github.event_name == 'pull_request'

  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for forbidden patterns
        run: |
          VIOLATIONS=0

          # Check for DEX integration
          if grep -rn "uniswap\|sushiswap\|pancakeswap" --include="*.sol" --include="*.ts" 2>/dev/null; then
            echo "::error::DEX integration detected"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          # Check for hardcoded secrets
          if grep -rn "private.*key.*=.*['\"]0x\|mnemonic.*=.*['\"]" --include="*.ts" --include="*.js" 2>/dev/null; then
            echo "::error::Hardcoded secrets detected"
            VIOLATIONS=$((VIOLATIONS + 1))
          fi

          # Check for FIAT handling
          if grep -rn "stripe\|paypal\|bank_transfer" --include="*.ts" --include="*.js" 2>/dev/null; then
            echo "::warning::Direct FIAT handling detected"
          fi

          if [ $VIOLATIONS -gt 0 ]; then
            exit 1
          fi

  notify-master:
    name: Notify Master
    runs-on: ubuntu-latest
    needs: [lint, test, build, security, compliance-check]
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Report to Master
        run: |
          echo "CI completed for ${{ github.repository }}"
          echo "Status: ${{ needs.build.result }}"
          # In production, this would notify the master repo
